on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemo12345.azurecr.io
        username: ${{ secrets.acr_acrdemo12345_username }}
        password: ${{ secrets.acr_acrdemo12345_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrdemo12345.azurecr.io/aksdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrdemo12345.azurecr.io/aksdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-demo910b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-demo910b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-demo910b
        container-registry-url: acrdemo12345.azurecr.io
        container-registry-username: ${{ secrets.acr_acrdemo12345_username }}
        container-registry-password: ${{ secrets.acr_acrdemo12345_password }}
        secret-name: aksdemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-demo910b
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          acrdemo12345.azurecr.io/aksdemo:${{ github.sha }}
        imagepullsecrets: |
          aksdemodockerauth
